# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates


# using group updates.
# Any packages matching the pattern @angular* where the highest resolvable
# version is minor or patch will be grouped together.
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
      bable:
        patterns:
        - "@bable*"
        update-types:
        - "major"

  # Use `ignore` to specify dependencies that should not be updated
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "django"
        versions: ["3.1.x", "4.x"]
      - dependency-name: "cryptography"
      - dependency-name: "requests"
        update-types: ["version-update:semver-patch"]


